# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17u0JZxsIQgrupAIVVBkR0dtoKync6-lr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

gender_submission_url = '/gender_submission.csv' # Update with your path
train_url = '/test.csv' # Update with your path
test_url = '/train.csv' # Update with your path

gender_submission = pd.read_csv(gender_submission_url)
train = pd.read_csv(train_url)
test = pd.read_csv(test_url)

print("First few rows of the gender submission dataset:")
print(gender_submission.head())

train['Age'].fillna(train['Age'].median(), inplace=True)
train['Embarked'].fillna(train['Embarked'].mode()[0], inplace=True)
train['Fare'].fillna(train['Fare'].median(), inplace=True)
train.drop(columns=['Cabin'], inplace=True)

test['Age'].fillna(test['Age'].median(), inplace=True)
test['Embarked'].fillna(test['Embarked'].mode()[0], inplace=True)
test['Fare'].fillna(test['Fare'].median(), inplace=True)
test.drop(columns=['Cabin'], inplace=True)

plt.figure(figsize=(10, 6))
sns.histplot(train['Age'], bins=30, kde=True)
plt.title('Age Distribution in Train Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=train, x='Sex')
plt.title('Gender Distribution in Train Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=train, x='Pclass')
plt.title('Passenger Class Distribution in Train Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=train, x='Pclass', y='Age')
plt.title('Age Distribution by Passenger Class in Train Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=test, x='Survived')
plt.title('Survival Distribution in Train Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=train, x='Pclass', y='Age')
plt.title('Age Distribution by Passenger Class in Train Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=test, x='Survived', y='Age')
plt.title('Age Distribution by Survival in Train Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=test, x='Pclass', hue='Survived')
plt.title('Survival by Passenger Class in Train Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=test, x='Sex', hue='Survived')
plt.title('Survival by Gender in Train Dataset')
plt.show()

plt.figure(figsize=(12, 8))
numeric_train = train.select_dtypes(include=[np.number])  # Select only numeric columns
sns.heatmap(numeric_train.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap in Train Dataset')
plt.show()

sns.pairplot(test.select_dtypes(include=[np.number]).dropna(), hue='Survived', diag_kind='kde')
plt.show()